config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'tags#index'
  get '/tags' => 'tags#index'
  get '/tags/:id' => 'tags#show', as: :tag
  get '/destinations/:id' => 'destinations#show', as: :destination
  get '/destinations/:id/edit' => 'destinations#edit', as: :edit_destination 
  patch '/destinations/:id' => 'destinations#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ActiveRecord::Base
	belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :destinations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
	def show
    @destination = Destination.find(params[:id])
  end

  def edit 
    @destination = Destination.find(params[:id]) 
  end

  def update 
  	@destination = Destination.find(params[:id]) 
  	if @destination.update_attributes(destination_params) 
      redirect_to(:action => 'show', :id => @destination.id) 
    else 
    	render 'edit' 
  	end 
  end

  private 
  def destination_params 
    params.require(:destination).permit(:name, :description) 
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @destinations = @tag.destinations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/destinations/edit.html.erb
<div class="header">
  <div class="container">
    <a href="/tags">
      <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
      <h1>BokenjiKan</h1>
    </a>
  </div>
</div>

<div class="destination">
  <div class="container">
    <%= image_tag @destination.image %>

    <%= form_for(@destination) do |f| %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>
      <div class="actions">
        <%= f.submit "Update" %>
      </div>
    <% end %>

  </div>
</div> 

app/views/destinations/show.html.erb
<div class="header">
  <div class="container">
    <a href="/tags">
      <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
      <h1>BokenjiKan</h1>
    </a>
  </div>
</div>

<div class="destination">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <img src="<%= @destination.image %>">
        <h2><%= @destination.name %></h2>
        <p><%= @destination.description %></p>
        <%= link_to "Edit", edit_destination_path() %>
      </div>
    </div>
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/tags/index.html.erb
<div class="header">
  <div class="container">
    <a href="/tags">
      <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
      <h1>BokenjiKan</h1>
    </a>
  </div>
</div>

<div class="tags">
  <div class="container">
    <div class="cards row">
    	<% @tags.each do |t| %>
      <div class="card col-xs-4">
        <%= image_tag t.image %>
        <h2><%= t.title %></h2>
        <%= link_to "Learn more", tag_path(t) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<div class="header">
  <div class="container">
    <a href="/tags">
      <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
      <h1>BokenjiKan</h1>
    </a>
  </div>
</div>

<div class="tag">
  <div class="container">
    <h2><%= @tag.title %></h2>

    <div class="cards row">
      <% @destinations.each do |d| %>
      <div class="card col-xs-4">
        <%= image_tag d.image %>
        <h2><%= d.name %></h2>
        <p><%= d.description %></p>
        <%= link_to "See more", destination_path(d) %>
      </div>
      <% end %>
    </div>

  </div>
</div>